print("შედარებითი ოპერატორები")
print(10>5)
print(10<5)
print(30>38)
print(23>23)
print(5>2)
print(20<100)
print(30<31)
print(100>200)
print(6>3)
print(58<68)

print("იოგიკური ოპერატორები")
print("true<false")
print("true>false")
print("false<true")
print("false>true")
print("false=true")
print("true=false")
print("false=false")
print("true=true")
print("true<true")
print("false>false")
print("false<false")
print("true>true")